$(document).ready(function(){
            $(".box").mouseenter(function(){
                $(".box1").hide();
                $(".box2").hide();
                $(".box3").hide();
            });
             $(".box").mouseleave(function(){
                $(".box1").show();
                $(".box2").show();
                $(".box3").show();
            });
        });
         $(document).ready(function(){
            $(".box1").mouseenter(function(){
                $(".box").hide();
                $(".box2").hide();
                $(".box3").hide();
            });
               $(".box1").mouseleave(function(){
                $(".box").show();
                $(".box2").show();
                $(".box3").show();
            });
        });
         $(document).ready(function(){
            $(".box2").mouseenter(function(){
                $(".box1").hide();
                $(".box").hide();
                $(".box3").hide();
            });
               $(".box2").mouseleave(function(){
                $(".box1").show();
                $(".box").show();
                $(".box3").show();
            });
        });
         $(document).ready(function(){
            $(".box3").mouseenter(function(){
                $(".box1").hide();
                $(".box2").hide();
                $(".box").hide();
            });
               $(".box3").mouseleave(function(){
                $(".box1").show();
                $(".box2").show();
                $(".box").show();
            });
        });